# -*- coding: utf-8 -*-
"""Airline Flight Data Analysis Using Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nlmdm09LxuTyQV9plkIMxCH3A3ijA_0v
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/airlines_flights_data.csv")
df

"""Cleaning the Data"""

df.drop(columns ='index', inplace=True)

df

#info about the data
df.info()

#Statitical summary
df.describe()

df[df['duration'] == 49.830000]

df[df['duration'] == 0.830000]

df[df['price'] == 123071.000000]

df[df['price'] == 1105.000000]

#CCheck null values
df.isnull().sum()

#Checking how many airlines in datset
df['airline'].unique()

#Showing all airlines with their Frequencies
df.airline.value_counts()

#Showing all Airlines with their number of flightsn in Bar Graph
df.airline.value_counts().plot(kind='bar' , color =['Green'])
plt.title('Airline with Frequencies')
plt.xlabel('Airlines')
plt.ylabel('Number of Airlines')
plt.show()

df.head()

#Showing departure time
df.departure_time.value_counts(ascending = True)

#Showing Arrival time
df.arrival_time.value_counts(ascending = True)

plt.figure(figsize=(16,4))  # set figure size first
plt.subplot(1,2,1)          # create subplot

plt.bar(df.departure_time.value_counts().index,
        df.departure_time.value_counts().values,
        color='grey')

plt.title('Departure Time')
plt.xlabel('D.Time')
plt.ylabel('Number of Flights')


plt.subplot(1,2,2)
plt.bar(df.arrival_time.value_counts().index,
        df.arrival_time.value_counts().values,
        color='brown')

plt.title('Arrival Time')
plt.xlabel('A.Time')
plt.ylabel('Number of Arrival Fligt')

plt.show()

#Show Bar Graph Source city and destination city
df.head()

#Showing source city of the flights
df.source_city.value_counts()

#showning destination city of the flights
df.destination_city.value_counts()

#Showing the source city & destination city for the flight with theri counts
plt.figure(figsize=(16,4))
plt.subplot(1,2,1)
plt.bar(df.source_city.value_counts().index,
        df.source_city.value_counts().values,
        color='y')

plt.title('Source City')
plt.xlabel('S City')
plt.ylabel('No of Flights')


plt.subplot(1,2,2)
plt.bar(df.destination_city.value_counts().index,
        df.destination_city.value_counts().values,
        color='r')

plt.title('Destination City')
plt.xlabel('D City')
plt.ylabel('No of Flights')

#Price Varies with Airline
df.head()

#Grouping  the Airline and check theri mean
df.groupby('airline')['price'].mean()

#Drawing a Cateogorcal Plot showing the mean ticket price for each airline

sns.catplot(
    x='airline',
    y='price',
    kind='bar',
    palette='rocket',
    data=df,
    hue='class'
)

plt.show()

df.head()

#Checking the mean ticket price based on the departure time
df.groupby('departure_time')['price'].mean()

#Checking the mean ticket price based on the arrival time
df.groupby('arrival_time')['price'].mean()

g = sns.catplot(
    x='departure_time',
    y='price',
    kind='bar',
    data=df,
)

# Rotate x-axis labels for readability
g.set_xticklabels(rotation=45)
plt.show()

g = sns.catplot(
    x='arrival_time',
    y='price',
    kind='bar',
    data=df,
)

# Rotate x-axis labels for readability
g.set_xticklabels(rotation=45)
plt.show()

sns.relplot(x ='arrival_time', y='price', data=df, col='departure_time', kind='line' )
plt.show()

#checking the mean ticket price for each Source city
df.groupby('source_city')['price'].mean()

#checking the mean ticket price for each Destination city
df.groupby('destination_city')['price'].mean()

sns.relplot(x ='destination_city', y='price', data=df, col='source_city', kind='line' )
plt.show()

df.head()

df.days_left.nunique()

df.days_left.unique()

#Checking the mean Ticket price for differrnt days_left
df.groupby('days_left')['price'].mean()

sns.relplot(x ='days_left', y='price', data=df, kind='line' )
plt.show()

df.head()

df['class'].unique()

x = df[df['class'] == 'Economy']
y = df[df['class'] == 'Business']
print(x,y)

#Economy
x.price.mean()

#Business
y.price.mean()

